apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: static-webserver
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nodeplusplus/fluxcd
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
