apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: me
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: mirantis
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: "true"
      hosts:
        - host: me.opsplusplus.local
          paths:
            - /
